### ISSUE TITLE
Missing AWS Cost Anomaly Detection in "Related services"

### ISSUE THREAD

**Issue by ad-m-ss** [awsdocs/aws-chatbot-admin-guide#3]
See https://aws.amazon.com/about-aws/whats-new/2022/03/aws-cost-anomaly-detection-integration-chatbot/

The lack of mention in this regard - with the mention of AWS Cost Explorer - was extremely confusing to me. I implemented already a workaround on my end around AWS EventBridge Pipes. I discovered this announcement by accident.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
